Add alsa support.
livejs/read-audio pull request #11
Opened 2017-02-08 17:30 UTC by gpgabriel

2017-02-09 06:11 UTC, ahdinosaur requested changes
hey @gpgabriel, thanks for this contribution. :smile_cat: 

keen to support `alsa`, but first gave some feedback.

cheers!

2017-02-09 06:11 UTC, ahdinosaur commented on main.js
> +      ps = spawn(
what if instead of `os.platform() !== 'darwin'`, we check that `arecord` path exists to run this code path?

2017-02-09 06:11 UTC, ahdinosaur commented on main.js
> +        [ '--buffer', opts.buffer, '--bits', opts.bits, '--channels', opts.channels,
unnecessary formatting change

2017-02-09 06:11 UTC, ahdinosaur commented on main.js
> +  var ps;
you can do `var ps =` in both code paths, no problem. or this is fine too.

2017-02-09 06:11 UTC, ahdinosaur commented on main.js
> +var toPull = require('stream-to-pull-stream');
unnecessary changes to add all the semicolons

2017-02-09 12:18 UTC, gpgabriel commented
@ahdinosaur Thanks for the detailed review. Let me know if there's anything else that you think could be improved.

2017-02-10 06:45 UTC, ahdinosaur approved these changes
thanks for incorporating the feedback @gpgabriel, looks great meow.

2017-02-10 06:45 UTC, ahdinosaur commented on main.js
> +var os = require('os')
no longer used

2017-02-10 06:55 UTC, merged

2017-02-10 07:11 UTC, ahdinosaur commented
published as [`8.1.0`](https://github.com/ahdinosaur/read-audio/commit/fe28262866c9b6c29a0ea9744d40a72dd983e5fc)